### PR TITLE
bitecs misrepresentation fixes

### PR DESCRIPTION
**Pull request by NateTheGreatt**
the previous implementation of bitecs into this repo was misrepresenting bitecs's iteration performance. thank you @octavetoast for adding bitecs here, but please be careful with the implementation next time ❤️ 

A) implementation was not identical to the other lib bench suites
B) implementation was also using a version of the API which is about to become deprecated

this PR addresses those two points by properly implementing the bench suite, additionally with the new `bitecs@alpha` API

bitecs will always (for now at least) out-perform object-based implementations in iteration speed due to its use of TypedArrays for component data stores. bitecs can also handle **many millions** of entities for this reason, which is something that object-based implementations cannot achieve without blowing the heap.

```

Suite Add/Remove (5000 iterations)
  - fastecs         12ms     58414ms   15000 updates       0.0% fastest
  - bitecs          26ms    130762ms25010000 updates     123.9% slower       
  - uecs            60ms    298397ms25010000 updates     410.8% slower       
  - geotic (v4)     65ms    323106ms25010000 updates     453.1% slower       
  - perform-ecs     70ms    352001ms25010000 updates     502.6% slower       
  - tiny-ecs       146ms    728251ms25010000 updates    1146.7% slower       
  - yagl-ecs       166ms    829415ms25010000 updates    1319.9% slower       
  - nano-ecs       226ms   1129940ms25010000 updates    1834.4% slower       
  - ape-ecs        468ms   2338441ms25010000 updates    3903.2% slower       
  - geotic (v3)   2368ms  11838450ms25010000 updates   20166.5% slower       

Suite Additions (100000 iterations)
  - bitecs           4ms    367036ms       0.0% fastest
  - yagl-ecs         4ms    408517ms      11.3% slower
  - uecs             5ms    502133ms      36.8% slower
  - tiny-ecs         5ms    504082ms      37.3% slower
  - fastecs          5ms    535749ms      46.0% slower
  - nano-ecs         6ms    551073ms      50.1% slower
  - perform-ecs      7ms    666837ms      81.7% slower
  - geotic (v4)      7ms    698764ms      90.4% slower
  - ape-ecs         10ms   1028666ms     180.3% slower
  - geotic (v3)     14ms   1429130ms     289.4% slower

Suite Destroy (100000 iterations)
  - bitecs           4ms    378292ms       0.0% fastest
  - fastecs          6ms    557217ms      47.3% slower
  - tiny-ecs         6ms    557675ms      47.4% slower
  - uecs             6ms    567944ms      50.1% slower
  - nano-ecs         6ms    632398ms      67.2% slower
  - perform-ecs      7ms    654627ms      73.0% slower
  - geotic (v4)      8ms    841428ms     122.4% slower
  - ape-ecs         13ms   1276946ms     237.6% slower
  - geotic (v3)     17ms   1691611ms     347.2% slower
  - yagl-ecs        28ms   2782902ms     635.6% slower

Suite Velocity (2000 iterations)
  - bitecs          13ms     26011ms 2001000 updates       0.0% fastest      
  - uecs            15ms     29825ms 2001000 updates      14.7% slower       
  - perform-ecs     17ms     34710ms 2001000 updates      33.4% slower       
  - tiny-ecs        19ms     37733ms 2001000 updates      45.1% slower       
  - geotic (v4)     19ms     37806ms 2001000 updates      45.3% slower       
  - fastecs         20ms     40715ms 2001000 updates      56.5% slower       
  - nano-ecs        24ms     48451ms 2001000 updates      86.3% slower       
  - yagl-ecs        35ms     70012ms 2001000 updates     169.2% slower       
  - ape-ecs        113ms    226979ms 2001000 updates     772.6% slower       
  - geotic (v3)    397ms    794807ms 2001000 updates    2955.7% slower       

  ```
  
  p.s. thank you for creating this bench repo @ddmills!

### CODE REVIEW

**Comment by octavetoast** [comment]
Thank you for reviewing my PR, apologies for mis-representing the repo.

Although I do agree that bitecs may always been faster than any of these other implementations, I don't think we shouldn't include it in the benchmark. Object-based implementations can still beat typed-arrays if querying/storage is done correctly (see @javelin/ecs).

**Comment by NateTheGreatt** [comment]
>  Object-based implementations can still beat typed-arrays if querying/storage is done correctly (see @javelin/ecs).

personally i've never been able to make object-based storage go as fast as typedarray-based. last time I benched javelin/ecs it still underperformed bitecs. i'll have to check if it has changed since then.

**Comment by NateTheGreatt** [comment]
@octavetoast i forgot, it has been benched in another repo with bitecs:
https://github.com/noctjs/ecs-benchmark

certainly impressively fast for object-based storage! unfortunately still quite a bit slower than bitecs

**Comment by octavetoast** [comment]
TypedArray implementations will always be faster, but sometimes micro-optimizations like that aren't necessary. I'd still use an object-based implementation because they're easier to understand and type.

**Comment by NateTheGreatt** [comment]
@octavetoast for sure! bitecs was specifically made for and tailored to a multi-threaded and auto-networked game engine/editor in the works, so the API is biased towards that use-case.

**Comment by octavetoast** [comment]
I honestly prefer writing my own game server/client implementations over using the ECS pattern, although I do think it has it's uses. ECS tries to solve the problem of inheritance, but there are better ways to go about it without sacrificing true OOP.

**Comment by NateTheGreatt** [comment]
> ECS tries to solve the problem of inheritance, but there are better ways to go about it without sacrificing true OOP.

i wouldn't say that ECS is trying solving the problem of inheritance at all. however, there are ways to represent hierarchies with ECS. `flecs` has some very performant, impressive, and inspiring work around hierarchical entity representation possibilities in ECS:
https://www.flecs.dev/query_demo

**Comment by octavetoast** [comment]
Well, it's not, but a lot of people praise it for being a solution to long inheritance chains. I don't think inheritance belongs in ECS, I think it might even break the rules. That's like using schemas in a document-based database.

**Review by ddmills — APPROVED** [review]
neat! thank you for contributing and good discussion 👍

**Comment by 3mcd** [comment]
A few days late to the party but I just wanted to chime in. TypedArray implementations will probably always be faster than object-based ECS in terms of iteration performance. I have mostly anecdotal evidence to back this claim but FWIW I've spent hundreds of hours of fiddling with this stuff. So, if your game is truly CPU-bound and your systems iterate many (>10^5) entities per 16ms tick, I can see a good argument to be made to choose a library like BitECS over alternatives on the basis of performance (although, at that point you may want to also start considering using WASM bindings into a library like [Flecs](https://github.com/WEREMSOFT/c99-flecs-wasm-example)).

BTW, it's awesome that `SharedArrayBuffer` can be used as a built-in storage type in BitECS and will make multithreading super easy to support and implement in your game! Of course, multithreading is still possible using other JS ECS libraries 😄

**Pull request merged**
